eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}  #whenever there is environment variable, with EUREKA_SERVER_ADDRESS, it will use EUREKA_SERVER_ADDRESS otw it uses http://localhost:8761/eureka
